#=-= Define Interface Modules =-=
[interface.dummy]
    module="testing"
    class="Dummy"
[interface.dummy.config]

#=-= Define Device Modules =-=
[device.adc_0]
    module="testing"
    class="MockDeviceRandom"
    interface="dummy"
[device.adc_0.config]
    min=18000
    max=20000
[device.adc_0.variables]
    variable = "v_amp_out"

[device.adc_1]
    module="testing"
    class="MockDeviceRandom"
    interface="dummy"
[device.adc_1.config]
    min=16000
    max=18000
[device.adc_1.variables]
    variable = "v_amp_out"

[device.adc_2]
    module="testing"
    class="MockDeviceRandom"
    interface="dummy"
[device.adc_2.config]
    min=16000
    max=19000
[device.adc_2.variables]
    variable = "v_amp_out"

#=-= Define Calculation Modules =-=
[calculation.machine_name]
    module="gen_constants"
    class="ConstantSet"
[calculation.machine_name.config]
    machine = "Machine_1"
[calculation.machine_name.variables]

[calculation.rms_current]
    module="gen_electrical"
    class="RMSToPeak"
[calculation.rms_current.variables]
    var_in = "current_rms"
    var_out = "clamp_current"

[calculation.current_clamp]
    module="gen_current_clamp"
    class="VoltageClamp"
[calculation.current_clamp.config]
    nominal_current = 10
[calculation.current_clamp.variables]
    current_in = "clamp_current"
    voltage_out = "v_amp_in"

[calculation.amplifier]
    module="gen_amplifier"
    class="GenAmplifier"
[calculation.amplifier.config]
    gain = 2
[calculation.amplifier.variables]
    amp_input = "v_amp_in"
    amp_output = "v_amp_out"

#=-= Define Calculation Pipelines =-=
[pipelines]
    rms_current = ["rms_current","current_clamp","amplifier","machine_name"]

#=-= Define Measurements Pipelines =-=
[measurement]
    module="gen_sample"
    class="MultiSampleIndividualAvg"
[measurement.config]
    period = 1.0 # seconds
    n_samples = 5
[[measurement.sensing_stacks]]
    device = "adc_0"
    pipeline = "rms_current"
    constants = {'phase'='A'}
[[measurement.sensing_stacks]]
    device = "adc_1"
    pipeline = "rms_current"
    constants = {'phase'='B'}
[[measurement.sensing_stacks]]
    device = "adc_2"
    pipeline = "rms_current"
    constants = {'phase'='C'}


[output.phase]
    topic = "power_monitoring/{{machine}}/{{phase}}"
[output.phase.message_spec]
    machine = "$.machine"
    timestamp = '$.timestamp'
    current = "$.current_rms"
    phase = "$.phase"

[mqtt]
    broker = "mqtt.docker.local"
    port = 1883   #common mqtt ports are 1883 and 8883
    topic_prefix = ""

    #reconnection characteristics
    # start: timeout = initial,
    # if timeout < limit then
    #   timeout = timeout*backoff
    # else
    #   timeout = limit
    reconnect.initial = 5 # seconds
    reconnect.backoff = 2 # multiplier
    reconnect.limit = 60 # seconds
