#   Select the config file (by removing the leading #) appropriate for your hardware and wiring setup
module_config_file = "./config/temperature_sequent_rtd.toml"

# Set the machine name
calculation.machine_name.config.machine = "Machine_Name_Here"

# Set which channel the RTD is plugged into.
device.adc_0.config.channel = 1
